// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(EfCoreContext))]
    [Migration("20231108212327_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.CustomerInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("CustomerInformation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "etstedidanmark",
                            Country = "Denmark",
                            OrderId = 1
                        });
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardDetails")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("CustomerInformationId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SocialSecurity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardDetails = "1234567891234567",
                            CustomerInformationId = 0,
                            Email = "a@gmail.com",
                            OrderDate = new DateTime(2023, 11, 8, 21, 23, 26, 88, DateTimeKind.Utc).AddTicks(8940),
                            PokemonId = 1,
                            Price = 0.0,
                            SocialSecurity = "1234567891"
                        });
                });

            modelBuilder.Entity("Data.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Sprite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Pokemon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bulbasaur",
                            Sprite = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ivysaur",
                            Sprite = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Venusaur",
                            Sprite = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Charmander",
                            Sprite = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Charmeleon",
                            Sprite = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charizard",
                            Sprite = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"
                        });
                });

            modelBuilder.Entity("Data.Entities.PokemonStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("PokemonId")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId")
                        .IsUnique();

                    b.ToTable("PokemonStats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A grass and poison type Pokémon.",
                            Experience = 64,
                            Height = 7,
                            PokemonId = 1,
                            Weight = 69
                        },
                        new
                        {
                            Id = 2,
                            Description = "Evolution of Bulbasaur.",
                            Experience = 100,
                            Height = 10,
                            PokemonId = 2,
                            Weight = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Final evolution of Bulbasaur.",
                            Experience = 103,
                            Height = 13,
                            PokemonId = 3,
                            Weight = 130
                        },
                        new
                        {
                            Id = 4,
                            Description = "A fire-type Pokémon.",
                            Experience = 120,
                            Height = 6,
                            PokemonId = 4,
                            Weight = 85
                        },
                        new
                        {
                            Id = 5,
                            Description = "Evolution of Charmander.",
                            Experience = 140,
                            Height = 11,
                            PokemonId = 5,
                            Weight = 190
                        },
                        new
                        {
                            Id = 6,
                            Description = "Final evolution of Charmander.",
                            Experience = 200,
                            Height = 17,
                            PokemonId = 6,
                            Weight = 905
                        });
                });

            modelBuilder.Entity("Data.Entities.CustomerInformation", b =>
                {
                    b.HasOne("Data.Entities.Order", "Order")
                        .WithOne("CustomerInformation")
                        .HasForeignKey("Data.Entities.CustomerInformation", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Data.Entities.Pokemon", b =>
                {
                    b.HasOne("Data.Entities.Order", null)
                        .WithMany("Pokemon")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Data.Entities.PokemonStats", b =>
                {
                    b.HasOne("Data.Entities.Pokemon", "Pokemon")
                        .WithOne("PokemonStats")
                        .HasForeignKey("Data.Entities.PokemonStats", "PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Data.Entities.Order", b =>
                {
                    b.Navigation("CustomerInformation")
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Data.Entities.Pokemon", b =>
                {
                    b.Navigation("PokemonStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
